# Generated by Django 4.2.2 on 2023-07-03 05:10

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(default='images/default.png', upload_to='media\\images', validators=[app.models.ProfileModel.validate_file_size]),
        ),
        migrations.DeleteModel(
            name='ProfilePicModel',
        ),
    ]
