# Generated by Django 4.2.2 on 2023-07-03 05:16

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profilemodel_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media\\images', validators=[app.models.ProfileModel.validate_file_size]),
        ),
    ]
