# Generated by Django 4.2.2 on 2023-07-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profilemodel_about_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='Designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
