# Generated by Django 4.2.2 on 2023-07-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profilemodel_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='Designation',
            new_name='designation',
        ),
    ]
